### PR TITLE
add cuteness

### PR DESCRIPTION
**Pull request by willeccles**

### CODE REVIEW

**Comment by vizs** [comment]
uwu

**Comment by ym1234** [comment]
brb deleting repo

**Comment by fr3fou** [comment]
uwu

**Comment by Renzix** [comment]
Merge or i unstar

**Comment by ym1234** [comment]
unstar and i block :p

**Comment by Renzix** [comment]
Done

**Comment by vizs** [comment]
when merge😳

**Comment by ym1234** [comment]
Needs tests

**Comment by vizs** [comment]
1984😔

**Pull request closed without merging**
